정렬
Altu-Bitu-2/Altu-Bitu-Doh pull request #1
Opened 2022-03-10 03:18 UTC by sohyundoh

### 내용 & 질문

> 12840번 백준에서는 틀렸다고 나오는데 이유를 모르겠습니다!

### 기존 제출

> 1026,10804,12840

### 추가제출

> 1758, 1431

2022-03-10 11:43 UTC, mkwkw requested changes
과제 하시느라 고생 많으셨습니다!
1758번은 "틀렸습니다"가 나와서 p1으로 수정이 필요한 부분 코멘트 작성하였습니다.
p2, p3로 규칙 및 참고하면 좋을 부분 코멘트로 작성하였습니다!
그리고 코드 전체적으로 주석이 없습니다. 이 코드를 왜 작성하였는지를 주석으로 작성하시면 코드 흐름 이해 및 코드 작성에 도움이 됩니다.

또한, 커밋 기록을 보니 디렉토리를 생성하셨다가 지우면서 1026,10804,12840번이 pr에 들어오지 않은 것 같습니다. 이 세 문제 다시 커밋 부탁드립니다! 그래야 제가 리뷰를 해드릴 수 있어요~

2022-03-10 11:43 UTC, mkwkw commented on [정렬] 3월 4일/1431.cpp
> +        if ('0' <= B[i] && B[i] <= '9')    B_sum += B[i] - '0';
p3. c++에는 숫자인지 아닌지를 판별하는 isdigit()함수가 있어요! 한번 알아보시는 것도 추천합니다.

2022-03-10 11:43 UTC, mkwkw commented on [정렬] 3월 4일/1758.cpp
> +int money(int n, vector<int> arr) {
p2. 매개변수에는 참조값& 사용하는 것이 좋습니다.

2022-03-10 11:43 UTC, mkwkw commented on [정렬] 3월 4일/1758.cpp
> +}
p1. result의 최댓값은 어떻게 될까요? 자료형의 범위를 유의해주세요!

2022-03-10 11:43 UTC, mkwkw commented on [정렬] 3월 4일/1431.cpp
> +#define max_num 1000 + 1
p2. 상수의 이름은 전부 대문자로 하는 것이 규칙입니다!

2022-03-10 11:47 UTC, mkwkw commented
그리고 참고로 오늘까지는 기존 제출 범위에 해당 됩니다. 추가제출은 샘플 코드의 각 줄마다 주석을 작성하셔서 제출하시는 것입니다!

2022-03-10 11:57 UTC, sohyundoh commented
> m

감사합니다! 안 올라간 문제들 커밋해서 올렸습니다!

2022-03-10 11:58 UTC, sohyundoh commented on [정렬] 3월 4일/1758.cpp
> +}
감사합니다!

2022-03-10 13:41 UTC, mkwkw requested changes
전체적으로 주석이 없습니다. 주석을 작성하는 습관은 필요합니다!
코멘트 바탕으로 수정해주세요. 오늘 자정 전에 수정하신다면 오른쪽 상단의 re-request review 눌러주시고 오늘 자정 이후에 제출하시려면 추가제출로 샘플 코드에 주석 달아서 제출해주세요!

2022-03-10 13:41 UTC, mkwkw commented on [정렬] 3월 4일/10804.cpp
> +		reverse(arr + a - 1, arr + b); //sort �Լ� ����ϰ� �;�µ� ����° ���ڷ� ����� �־������ �𸣰ڽ�ϴ�.
p3. 이미 arr이 오름차순으로 정렬이 되어있으므로 여기서는 sort함수를 다시 쓰지 않아도 됩니다!

2022-03-10 13:41 UTC, mkwkw commented on [정렬] 3월 4일/12840.cpp
> +}
p1.  각 함수에서 초를 시, 분, 초로 매번 바꾸는 것보다 main에서 시,분,초를 입력 받을 때, 초로 통일해서 변환하면 덜 복잡해질 것 같습니다. 그리고 계속 0시 0분 0초에서 23시 59분 59초까지의 범위 내에서 돌아야합니다. 각 함수에서 모듈러 연산(%)을 한 번씩 더 사용하면 될 것 같아요! 그리고 24시간이 총 몇 초인지도 고려해주셔야합니다.

2022-03-10 14:04 UTC, sohyundoh commented on [정렬] 3월 4일/12840.cpp
> +}
24시간이 총 몇초인지는 왜 고려해야하나요??

2022-03-11 03:14 UTC, mkwkw requested changes
p1. 12840 수정하실 부분 코멘트 작성했습니다~

2022-03-11 03:14 UTC, mkwkw commented on [정렬] 3월 4일/12840.cpp
> +}
만약에 하루가 넘는 시간이 입력으로 여러번 복잡하게 주어질 경우 23시 59분 59초에서 0시 0분 0초로 넘어가는 과정에서 오류가 발생할 수 있기 때문입니다!

2022-03-11 03:14 UTC, mkwkw commented on [정렬] 3월 4일/12840.cpp
> +}
그리고 출력할 때에도 시의 범위가 0에서 23까지, 분의 범위가 0에서 59까지인 점도 고려해서 수정하셔야합니다. 지금은 시 부분에는 모듈러 연산이 들어가있지 않고 분 부분에는 나누기 연산과 모듈러 연산이 잘못 들어가있습니다.

2022-03-11 03:20 UTC, mkwkw commented
결론적으로 출력할 때, 시와 분 부분의 식만 수정하시면 됩니다.
또한, 이렇게만 수정하면 시간초과가 뜨기때문에 slack의 공지에 있는 시간 향상 부분 (https://2-k965059.slack.com/archives/C034JHN1YF4/p1646806690484859) 참고하셔서 작성해주시면 통과됩니다.

2022-03-11 12:45 UTC, mkwkw commented
12840번 해결되지 않으신다면 오늘 밤 12시 전까지 추가제출 해주세요~

2022-03-11 12:56 UTC, sohyundoh commented
> 12840번 해결되지 않으신다면 오늘 밤 12시 전까지 추가제출 해주세요~

해결해서 커밋했는데 다른 방법으로 제출해야하나요??

2022-03-11 14:30 UTC, mkwkw commented
아닙니다! p1 사항이었으므로 수정하신 걸로 커밋하고 머지하시면 됩니다. 그런데 지금 branch에서 conflict가 난 것 같아요. resolve conflicts 해보시고 안 되면 다른 브랜치 만드셔서 pr하시고 바로 머지해주세요!

2022-03-11 14:40 UTC, merged